### ISSUE TITLE
hello: missing comment header.

### ISSUE THREAD

**Issue by lcabrini** [kelvinklufio/kelvin-linux-learning#3]
The hello script does not have a comment header. Please add one, as it is customary to give a short introduction to the script. At least include a short description of what the program does, your name and email.

Here is an example that you could use as a template:

```
# hello.sh -- print a greeting to the screen
# 
# Author: Lorenzo Cabrini <lorenzo.cabrini@gmail.com>
# Date created: 25 June 2015
```

**Comment by kelvinklufio** [comment]
made some changes to the hello.sh script. i added comments to the script to make it easier for people to figure what the script does by looking at it
